### PR TITLE
add dependency nativescript-vue-3

### PR DESCRIPTION
**Pull request by vallemar**
I thought we could have vue 3 with an alias so we can still maintain vue 2

### CODE REVIEW

**Comment by vallemar** [comment]
@farfromrefug if you agree with this approach but prefer the `nativescript-vue3` alias I can change it too, just let me know

**Comment by farfromrefug** [comment]
@vallemar i like the idea. let s go for `nativescript-vue3`
Do you have a vue3 app template? i can add it so we can start create vue3 demos

**Comment by vallemar** [comment]
@farfromrefug it's already changed. There is an official vue3 template here: https://github.com/nativescript-vue/nativescript-vue/tree/main/packages/template-blank

To add them we should add another repository like https://github.com/nativescript-community/plugin-seed-demo-vue but with vue3 and add another entry here https://github.com/nativescript-community/ui-material-components/tree/master/demo-snippets?

**Comment by farfromrefug** [comment]
@vallemar yes that is exactly that. Do you want to do it all? (you ve been invited to nativescript-community). I think you can create a repo now

**Comment by vallemar** [comment]
Yes, I will try to do it today. Now that's better, so I can make branches directly and we can have the same branch together

**Comment by farfromrefug** [comment]
@vallemar btw if you feel it does not need reviews dont hesitate to commit directly

**Pull request merged**
